var myString;
var myNum;
var myBool;
var myVar;
myString = 'Hello World';
myNum = 22;
myBool = true;
myVar = 3 + 'dhue';
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
strArr = ['Hello', 'World'];
numArr = [56, 3];
boolArr = [true, false];
var strNumTuple;
strNumTuple = ['Hello', 4];
// let myVoid: void = null;
// let myNull: null = null;
// let myUndefined: undefined = null;
var myVoid = undefined;
var myNull = undefined;
var myUndefined = undefined;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
